export const META_WEIGHTS: Record<string, Record<string, number>> = {
  C: {
    contact_right: 0.2,
    contact_left: 0.15,
    power_right: 0.15,
    power_left: 0.1,
    fielding: 0.15,
    arm_strength: 0.15,
    speed: 0.1,
  },
  '1B': {
    contact_right: 0.15,
    contact_left: 0.1,
    power_right: 0.25,
    power_left: 0.2,
    fielding: 0.1,
    arm_strength: 0.05,
    speed: 0.15,
  },
  '2B': {
    contact_right: 0.2,
    contact_left: 0.15,
    power_right: 0.1,
    power_left: 0.05,
    fielding: 0.2,
    arm_strength: 0.05,
    speed: 0.25,
  },
  '3B': {
    contact_right: 0.15,
    contact_left: 0.1,
    power_right: 0.25,
    power_left: 0.2,
    fielding: 0.15,
    arm_strength: 0.1,
    speed: 0.05,
  },
  SS: {
    contact_right: 0.2,
    contact_left: 0.15,
    power_right: 0.05,
    power_left: 0.05,
    fielding: 0.25,
    arm_strength: 0.1,
    speed: 0.2,
  },
  LF: {
    contact_right: 0.15,
    contact_left: 0.1,
    power_right: 0.2,
    power_left: 0.15,
    fielding: 0.1,
    arm_strength: 0.1,
    speed: 0.2,
  },
  CF: {
    contact_right: 0.15,
    contact_left: 0.1,
    power_right: 0.15,
    power_left: 0.1,
    fielding: 0.15,
    arm_strength: 0.1,
    speed: 0.25,
  },
  RF: {
    contact_right: 0.15,
    contact_left: 0.1,
    power_right: 0.2,
    power_left: 0.15,
    fielding: 0.1,
    arm_strength: 0.15,
    speed: 0.15,
  },
  SP: {
    stamina: 0.15,
    hits_per_bf: 0.2,
    k_per_bf: 0.25,
    bb_per_bf: 0.1,
    hr_per_bf: 0.1,
    pitch_control: 0.2,
  },
  RP: {
    hits_per_bf: 0.25,
    k_per_bf: 0.3,
    bb_per_bf: 0.1,
    hr_per_bf: 0.1,
    pitch_control: 0.25,
  },
  CP: {
    hits_per_bf: 0.25,
    k_per_bf: 0.3,
    bb_per_bf: 0.1,
    hr_per_bf: 0.1,
    pitch_control: 0.25,
  },
};

export const ELITE_QUIRKS: string[] = [
  'Dead Red',
  'Outlier',
  'Unfazed',
  'Bomber',
];
